name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - name: ls lha
        run: ls -lha build/
      - name: change directory permission
        run: find build/ -type d -exec chmod 705 {} +
      - name: change file permission
        run: find build/ -type f -exec chmod 604 {} +
      - name: confirm ls lha
        run: ls -lha build/